Uris:
  BaseUrl: http://lab.local:8787
  MenshendSubdomain: menshend.
Space:
  Name: Genos
  Logo: http://orig01.deviantart.net/3585/f/2015/344/1/f/one_punch_man_genos_render_2_by_ayakayukihiro-d9jnh9e.png
  Description: Nebtex Laboratory