menshend:
  image: nebtex/menshend:latest
  volumes:
    - ./config.yml:/etc/menshend.yml
  restart: always
  links:
    - vault
    - portainer
    - mongo-express
    - pgweb
  env_file:
    - .menshend.env
  ports:
    - "80:8787"

vault:
  image: vault:latest
  restart: always
  expose:
    - "8200"
  env_file: 
    - .vault.env

portainer:
  image: portainer/portainer:latest
  command: --no-auth
  expose:
    - "9000"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /srv/docker/portainer:/data
  restart: always

mongo:
  image: mongo:latest
  restart: always
  expose:
    - "27017"

mongo-express:
  image: mongo-express:latest
  restart: always
  ports:
    - "8081"
  links:
    - mongo

postgres:
  image: postgres:latest
  environment:
    - POSTGRES_PASSWORD=postgres
  restart: always
  expose:
    - "5432"

pgweb:
  image: sosedoff/pgweb:latest
  restart: always
  image: sosedoff/pgweb
  expose: 
    - "8081" 
  links: 
    - postgres
  environment:
    - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable