menshend:
  image: nebtex/menshend:latest
  volumes:
    - ./config.yml:/etc/menshend.yml
  restart: always
  links:
    - vault
    - portainer
  env_file:
    - .menshend.env
  ports:
    - "80:8787"

vault:
  image: vault:latest
  restart: always
  ports:
    - "8200:8200"
  env_file: 
    - .vault.env

portainer:
  image: portainer/portainer:latest
  command: --no-auth
  ports:
    - "9000:9000"
  networks:
    - local
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /srv/docker/portainer:/data
  restart: always