menshend:
  image: nebtex/menshend:latest
  volumes:
    - ./config.yml:/etc/menshend.yml
  restart: always
  links:
    - vault:vault
  env_file:
    - .menshend.env
  ports:
    - "8787:8787"

vault:
  image: vault:latest
  restart: always
  hostname: vault
  ports:
    - "8200:8200"
  env_file: 
    - .vault.env
  